--------------------------------------------------------
--  파일이 생성됨 - 금요일-7월-05-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table USER0
--------------------------------------------------------

  CREATE TABLE "ORA_USER"."USER0" 
   (	"USER_ID" VARCHAR2(20 BYTE), 
	"USER_PW" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into ORA_USER.USER0
SET DEFINE OFF;
Insert into ORA_USER.USER0 (USER_ID,USER_PW,NAME) values ('AA','123123','AA');
Insert into ORA_USER.USER0 (USER_ID,USER_PW,NAME) values ('AAA','123123','AAA');
Insert into ORA_USER.USER0 (USER_ID,USER_PW,NAME) values ('A','123123','A');
Insert into ORA_USER.USER0 (USER_ID,USER_PW,NAME) values ('김경래','123','김경래');
--------------------------------------------------------
--  DDL for Index USER0_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ORA_USER"."USER0_PK" ON "ORA_USER"."USER0" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table USER0
--------------------------------------------------------

  ALTER TABLE "ORA_USER"."USER0" ADD CONSTRAINT "USER0_PK" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ORA_USER"."USER0" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "ORA_USER"."USER0" MODIFY ("USER_PW" NOT NULL ENABLE);
  ALTER TABLE "ORA_USER"."USER0" MODIFY ("NAME" NOT NULL ENABLE);
